# docker-compose.yml
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
       - ./database/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend
    container_name: backend
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydb?schema=public
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
        restart: true
    links:
      - db
    entrypoint: /usr/src/app/entrypoint.sh
    dns:
      - 8.8.8.8
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 80:80
    links:
      - backend